### PR TITLE
Users avatars, minor css adjustments, fixes

### LINKED ISSUE #184: Display user avatar
Display user avatar everywhere where needed.

We should think of more performant way of displaying avatars, as currently we need to make 1 request to check if the user has avatar and then fetch the image with second request.

Maybe we can add the default avatar in the backend and have it displayed for every user that has no avatar (currently we keep it as local asset) - this way we will only make a single request for getting avatar image per user.

UPDATE: The backend now serves a fallback avatar image for user profile without custom avatar, so we are free to directly get and show the avatars from there.

### PR DESCRIPTION
**Pull request by mradkov**
- show user avatar dynamically (closes #184)
    - have getProfileImageUrl as `static` method as well
- adjust css for displaying avatar properly
- minor fixes:
    - onboarding wizzard tutorial link
    - onbosarding wizzard to be only visible if no wallet
    - trending leads to the main tiplistview

### CODE REVIEW

File: src/components/onboarding/steps/Step2.vue [hunk 1]
```diff
@@ -12,8 +12,8 @@
     <p>
       Fund transfers are instant, with near-zero processing fees.
       Censorship-proof: there are no third-party intermediaries to ban creators from sending and
-      receiving payments, and records are immortalized on æternity blockchain. Learn more by our
-      Tutorial & FAQ
+      receiving payments, and records are immortalized on æternity blockchain. <a href="https://youdonotneedacapetobeahero.com/#/create-profile" target="_blank">Learn more by our
```
Comment (venimus) [inline src/components/onboarding/steps/Step2.vue]: router?

Comment (mradkov) [reply src/components/onboarding/steps/Step2.vue]: Its intentionally by designers request like this - so you don't leave the wizzard.

Comment (venimus) [reply src/components/onboarding/steps/Step2.vue]: I guess we can use something like this to avoid bugs after domain migration
```
<router-link to="/create-profile" v-slot="{ href }"><a :href="href" "target=_blank">Tutorial & FAQ</a></router-link>
```

File: src/components/layout/SendTip.vue [hunk 2]
```diff
@@ -106,6 +107,17 @@ export default {
     clearTipForm() {
       this.sendTipForm = { amount: null, url: '', title: '' };
     },
+    getAvatar(address) {
+      return Backend.getProfileImageUrl(address);
+    },
+  },
+  async created() {
+    const loadUserAvatar = setInterval(() => {
```
Comment (venimus) [inline src/components/layout/SendTip.vue]: what is the issue here

Comment (mradkov) [reply src/components/layout/SendTip.vue]: Its related to #171.
